#\!/bin/bash

echo "🚀 DÉPLOIEMENT ATLAS PRODUCTION"
echo "================================"
echo ""

# Vérifier que nous avons le bon commit
echo "📋 Commit actuel local:"
git log --oneline -1

echo ""
echo "🔍 Vous devez maintenant vous connecter au serveur et exécuter:"
echo ""
echo "ssh root@atlas-invest.fr"
echo ""
echo "Puis, une fois connecté, exécutez:"
echo ""
echo "# 1. Aller dans le répertoire Atlas"
echo "cd /opt/atlas"
echo ""
echo "# 2. Vérifier l'état actuel"
echo "git status"
echo "git log --oneline -1"
echo ""
echo "# 3. Pull les dernières modifications"
echo "git pull origin main"
echo ""
echo "# 4. Vérifier le nouveau commit"
echo "git log --oneline -1"
echo ""
echo "# 5. Déployer avec Dokku"
echo "dokku git:sync atlas /opt/atlas"
echo "dokku ps:rebuild atlas"
echo ""
echo "# 6. Vérifier le déploiement"
echo "dokku logs atlas --tail"
echo ""
echo "# 7. Tester l'application"
echo "curl -I https://atlas-invest.fr"
echo ""
echo "✅ Si tout fonctionne, le déploiement est terminé \!"
echo ""
echo "🔧 En cas de problème:"
echo "dokku ps:restart atlas"
echo "dokku logs atlas --tail --num 50"

