#!/bin/bash

echo "🔧 CORRECTION NGINX - Instructions manuelles"
echo ""
echo "1️⃣  Connectez-vous au serveur :"
echo "ssh root@165.227.167.78"
echo "Mot de passe : (!=ZL@-nZu7eB?7a"
echo ""

echo "2️⃣  Démarrez l'application Flask :"
echo "su - appuser"
echo "cd /home/appuser/coach-patrimoine"
echo "source venv/bin/activate"
echo "pkill -f gunicorn || true"
echo "gunicorn --bind 127.0.0.1:5000 --workers 2 --daemon wsgi:app"
echo "exit"
echo ""

echo "3️⃣  Configurez Nginx :"
echo "cat > /etc/nginx/sites-available/coach-patrimoine << 'EOF'"
echo "server {"
echo "    listen 80;"
echo "    server_name _;"
echo "    "
echo "    location / {"
echo "        proxy_pass http://127.0.0.1:5000;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "        proxy_set_header X-Forwarded-Proto \$scheme;"
echo "    }"
echo "}"
echo "EOF"
echo ""

echo "4️⃣  Activez la configuration :"
echo "ln -sf /etc/nginx/sites-available/coach-patrimoine /etc/nginx/sites-enabled/"
echo "rm -f /etc/nginx/sites-enabled/default"
echo "nginx -t"
echo "systemctl restart nginx"
echo ""

echo "5️⃣  Testez :"
echo "curl http://localhost/"
echo "exit"
echo ""

echo "🌐 Votre site sera accessible à : http://165.227.167.78"